import { Routes } from './flight';

export const flights : Routes[] = [
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Mumbai",
    "destination_airport_id": 2,
    "destination_airport_code": "MUM",
    "price": 7910
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Delhi",
    "destination_airport_id": 3,
    "destination_airport_code": "DEL",
    "price": 8331
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Ahmedabad",
    "destination_airport_id": 4,
    "destination_airport_code": "AHM",
    "price": 7562
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Banglore",
    "destination_airport_id": 5,
    "destination_airport_code": "BAN",
    "price": 9793
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Hyderabad",
    "destination_airport_id": 6,
    "destination_airport_code": "HYD",
    "price": 6800
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Jaipur",
    "destination_airport_id": 7,
    "destination_airport_code": "JAI",
    "price": 6520
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "lucknow",
    "destination_airport_id": 8,
    "destination_airport_code": "LKW",
    "price": 5455
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Kolkata",
    "destination_airport_id": 9,
    "destination_airport_code": "KOL",
    "price": 3901
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Chennai",
    "destination_airport_id": 10,
    "destination_airport_code": "CHE",
    "price": 8908
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Goa",
    "destination_airport_id": 11,
    "destination_airport_code": "GOA",
    "price": 4834
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Mumbai",
    "destination_airport_id": 2,
    "destination_airport_code": "MUM",
    "price": 8081
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Delhi",
    "destination_airport_id": 3,
    "destination_airport_code": "DEL",
    "price": 7431
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Ahmedabad",
    "destination_airport_id": 4,
    "destination_airport_code": "AHM",
    "price": 4211
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Banglore",
    "destination_airport_id": 5,
    "destination_airport_code": "BAN",
    "price": 4752
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Hyderabad",
    "destination_airport_id": 6,
    "destination_airport_code": "HYD",
    "price": 5719
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Jaipur",
    "destination_airport_id": 7,
    "destination_airport_code": "JAI",
    "price": 7285
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "lucknow",
    "destination_airport_id": 8,
    "destination_airport_code": "LKW",
    "price": 2671
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Kolkata",
    "destination_airport_id": 9,
    "destination_airport_code": "KOL",
    "price": 3605
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Chennai",
    "destination_airport_id": 10,
    "destination_airport_code": "CHE",
    "price": 6461
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Goa",
    "destination_airport_id": 11,
    "destination_airport_code": "GOA",
    "price": 4452
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Mumbai",
    "destination_airport_id": 2,
    "destination_airport_code": "MUM",
    "price": 4203
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Delhi",
    "destination_airport_id": 3,
    "destination_airport_code": "DEL",
    "price": 2710
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Ahmedabad",
    "destination_airport_id": 4,
    "destination_airport_code": "AHM",
    "price": 7382
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Banglore",
    "destination_airport_id": 5,
    "destination_airport_code": "BAN",
    "price": 4631
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Hyderabad",
    "destination_airport_id": 6,
    "destination_airport_code": "HYD",
    "price": 9759
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Jaipur",
    "destination_airport_id": 7,
    "destination_airport_code": "JAI",
    "price": 7601
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "lucknow",
    "destination_airport_id": 8,
    "destination_airport_code": "LKW",
    "price": 7432
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Kolkata",
    "destination_airport_id": 9,
    "destination_airport_code": "KOL",
    "price": 2548
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Chennai",
    "destination_airport_id": 10,
    "destination_airport_code": "CHE",
    "price": 4933
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Goa",
    "destination_airport_id": 11,
    "destination_airport_code": "GOA",
    "price": 2527
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Mumbai",
    "destination_airport_id": 2,
    "destination_airport_code": "MUM",
    "price": 8430
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Delhi",
    "destination_airport_id": 3,
    "destination_airport_code": "DEL",
    "price": 8749
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Ahmedabad",
    "destination_airport_id": 4,
    "destination_airport_code": "AHM",
    "price": 9900
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Banglore",
    "destination_airport_id": 5,
    "destination_airport_code": "BAN",
    "price": 4670
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Hyderabad",
    "destination_airport_id": 6,
    "destination_airport_code": "HYD",
    "price": 6416
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Jaipur",
    "destination_airport_id": 7,
    "destination_airport_code": "JAI",
    "price": 7869
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "lucknow",
    "destination_airport_id": 8,
    "destination_airport_code": "LKW",
    "price": 3346
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Kolkata",
    "destination_airport_id": 9,
    "destination_airport_code": "KOL",
    "price": 7000
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Chennai",
    "destination_airport_id": 10,
    "destination_airport_code": "CHE",
    "price": 3146
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Goa",
    "destination_airport_id": 11,
    "destination_airport_code": "GOA",
    "price": 4296
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Mumbai",
    "destination_airport_id": 2,
    "destination_airport_code": "MUM",
    "price": 7170
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Delhi",
    "destination_airport_id": 3,
    "destination_airport_code": "DEL",
    "price": 9500
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Ahmedabad",
    "destination_airport_id": 4,
    "destination_airport_code": "AHM",
    "price": 4710
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Banglore",
    "destination_airport_id": 5,
    "destination_airport_code": "BAN",
    "price": 7002
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Hyderabad",
    "destination_airport_id": 6,
    "destination_airport_code": "HYD",
    "price": 6276
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Jaipur",
    "destination_airport_id": 7,
    "destination_airport_code": "JAI",
    "price": 3707
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "lucknow",
    "destination_airport_id": 8,
    "destination_airport_code": "LKW",
    "price": 3337
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Kolkata",
    "destination_airport_id": 9,
    "destination_airport_code": "KOL",
    "price": 9210
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Chennai",
    "destination_airport_id": 10,
    "destination_airport_code": "CHE",
    "price": 5848
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Goa",
    "destination_airport_id": 11,
    "destination_airport_code": "GOA",
    "price": 3954
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Mumbai",
    "destination_airport_id": 2,
    "destination_airport_code": "MUM",
    "price": 8566
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Delhi",
    "destination_airport_id": 3,
    "destination_airport_code": "DEL",
    "price": 6427
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Ahmedabad",
    "destination_airport_id": 4,
    "destination_airport_code": "AHM",
    "price": 7429
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Banglore",
    "destination_airport_id": 5,
    "destination_airport_code": "BAN",
    "price": 8310
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Hyderabad",
    "destination_airport_id": 6,
    "destination_airport_code": "HYD",
    "price": 7614
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Jaipur",
    "destination_airport_id": 7,
    "destination_airport_code": "JAI",
    "price": 2590
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "lucknow",
    "destination_airport_id": 8,
    "destination_airport_code": "LKW",
    "price": 8609
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Kolkata",
    "destination_airport_id": 9,
    "destination_airport_code": "KOL",
    "price": 9007
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Chennai",
    "destination_airport_id": 10,
    "destination_airport_code": "CHE",
    "price": 2785
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Pune",
    "source_airport_code": "PNQ",
    "source_airport_id": 1,
    "destination_airport": "Goa",
    "destination_airport_id": 11,
    "destination_airport_code": "GOA",
    "price": 6709
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Pune",
    "destination_airport_id": 1,
    "destination_airport_code": "PNQ",
    "price": 5066
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Delhi",
    "destination_airport_id": 3,
    "destination_airport_code": "DEL",
    "price": 5912
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Ahmedabad",
    "destination_airport_id": 4,
    "destination_airport_code": "AHM",
    "price": 9391
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Banglore",
    "destination_airport_id": 5,
    "destination_airport_code": "BAN",
    "price": 5846
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Hyderabad",
    "destination_airport_id": 6,
    "destination_airport_code": "HYD",
    "price": 7187
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Jaipur",
    "destination_airport_id": 7,
    "destination_airport_code": "JAI",
    "price": 4542
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "lucknow",
    "destination_airport_id": 8,
    "destination_airport_code": "LKW",
    "price": 9978
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Kolkata",
    "destination_airport_id": 9,
    "destination_airport_code": "KOL",
    "price": 5338
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Chennai",
    "destination_airport_id": 10,
    "destination_airport_code": "CHE",
    "price": 5562
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Goa",
    "destination_airport_id": 11,
    "destination_airport_code": "GOA",
    "price": 3767
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Pune",
    "destination_airport_id": 1,
    "destination_airport_code": "PNQ",
    "price": 4201
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Delhi",
    "destination_airport_id": 3,
    "destination_airport_code": "DEL",
    "price": 5726
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Ahmedabad",
    "destination_airport_id": 4,
    "destination_airport_code": "AHM",
    "price": 3397
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Banglore",
    "destination_airport_id": 5,
    "destination_airport_code": "BAN",
    "price": 3765
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Hyderabad",
    "destination_airport_id": 6,
    "destination_airport_code": "HYD",
    "price": 7210
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Jaipur",
    "destination_airport_id": 7,
    "destination_airport_code": "JAI",
    "price": 3497
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "lucknow",
    "destination_airport_id": 8,
    "destination_airport_code": "LKW",
    "price": 2315
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Kolkata",
    "destination_airport_id": 9,
    "destination_airport_code": "KOL",
    "price": 2313
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Chennai",
    "destination_airport_id": 10,
    "destination_airport_code": "CHE",
    "price": 7760
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Goa",
    "destination_airport_id": 11,
    "destination_airport_code": "GOA",
    "price": 2503
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Pune",
    "destination_airport_id": 1,
    "destination_airport_code": "PNQ",
    "price": 5915
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Delhi",
    "destination_airport_id": 3,
    "destination_airport_code": "DEL",
    "price": 5191
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Ahmedabad",
    "destination_airport_id": 4,
    "destination_airport_code": "AHM",
    "price": 7572
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Banglore",
    "destination_airport_id": 5,
    "destination_airport_code": "BAN",
    "price": 5728
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Hyderabad",
    "destination_airport_id": 6,
    "destination_airport_code": "HYD",
    "price": 7902
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Jaipur",
    "destination_airport_id": 7,
    "destination_airport_code": "JAI",
    "price": 3125
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "lucknow",
    "destination_airport_id": 8,
    "destination_airport_code": "LKW",
    "price": 2617
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Kolkata",
    "destination_airport_id": 9,
    "destination_airport_code": "KOL",
    "price": 9333
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Chennai",
    "destination_airport_id": 10,
    "destination_airport_code": "CHE",
    "price": 2293
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Goa",
    "destination_airport_id": 11,
    "destination_airport_code": "GOA",
    "price": 3112
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Pune",
    "destination_airport_id": 1,
    "destination_airport_code": "PNQ",
    "price": 4141
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Delhi",
    "destination_airport_id": 3,
    "destination_airport_code": "DEL",
    "price": 6707
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Ahmedabad",
    "destination_airport_id": 4,
    "destination_airport_code": "AHM",
    "price": 8647
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Banglore",
    "destination_airport_id": 5,
    "destination_airport_code": "BAN",
    "price": 4985
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Hyderabad",
    "destination_airport_id": 6,
    "destination_airport_code": "HYD",
    "price": 3366
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Jaipur",
    "destination_airport_id": 7,
    "destination_airport_code": "JAI",
    "price": 3564
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "lucknow",
    "destination_airport_id": 8,
    "destination_airport_code": "LKW",
    "price": 9362
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Kolkata",
    "destination_airport_id": 9,
    "destination_airport_code": "KOL",
    "price": 4305
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Chennai",
    "destination_airport_id": 10,
    "destination_airport_code": "CHE",
    "price": 6226
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Goa",
    "destination_airport_id": 11,
    "destination_airport_code": "GOA",
    "price": 5292
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Pune",
    "destination_airport_id": 1,
    "destination_airport_code": "PNQ",
    "price": 4184
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Delhi",
    "destination_airport_id": 3,
    "destination_airport_code": "DEL",
    "price": 6362
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Ahmedabad",
    "destination_airport_id": 4,
    "destination_airport_code": "AHM",
    "price": 3143
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Banglore",
    "destination_airport_id": 5,
    "destination_airport_code": "BAN",
    "price": 9751
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Hyderabad",
    "destination_airport_id": 6,
    "destination_airport_code": "HYD",
    "price": 5046
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Jaipur",
    "destination_airport_id": 7,
    "destination_airport_code": "JAI",
    "price": 4458
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "lucknow",
    "destination_airport_id": 8,
    "destination_airport_code": "LKW",
    "price": 8249
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Kolkata",
    "destination_airport_id": 9,
    "destination_airport_code": "KOL",
    "price": 8290
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Chennai",
    "destination_airport_id": 10,
    "destination_airport_code": "CHE",
    "price": 5507
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Goa",
    "destination_airport_id": 11,
    "destination_airport_code": "GOA",
    "price": 6718
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Pune",
    "destination_airport_id": 1,
    "destination_airport_code": "PNQ",
    "price": 3524
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Delhi",
    "destination_airport_id": 3,
    "destination_airport_code": "DEL",
    "price": 7213
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Ahmedabad",
    "destination_airport_id": 4,
    "destination_airport_code": "AHM",
    "price": 4315
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Banglore",
    "destination_airport_id": 5,
    "destination_airport_code": "BAN",
    "price": 8351
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Hyderabad",
    "destination_airport_id": 6,
    "destination_airport_code": "HYD",
    "price": 7289
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Jaipur",
    "destination_airport_id": 7,
    "destination_airport_code": "JAI",
    "price": 4872
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "lucknow",
    "destination_airport_id": 8,
    "destination_airport_code": "LKW",
    "price": 4506
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Kolkata",
    "destination_airport_id": 9,
    "destination_airport_code": "KOL",
    "price": 5173
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Chennai",
    "destination_airport_id": 10,
    "destination_airport_code": "CHE",
    "price": 9127
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Mumbai",
    "source_airport_code": "MUM",
    "source_airport_id": 2,
    "destination_airport": "Goa",
    "destination_airport_id": 11,
    "destination_airport_code": "GOA",
    "price": 9998
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Pune",
    "destination_airport_id": 1,
    "destination_airport_code": "PNQ",
    "price": 8836
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Mumbai",
    "destination_airport_id": 2,
    "destination_airport_code": "MUM",
    "price": 4993
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Ahmedabad",
    "destination_airport_id": 4,
    "destination_airport_code": "AHM",
    "price": 7336
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Banglore",
    "destination_airport_id": 5,
    "destination_airport_code": "BAN",
    "price": 7711
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Hyderabad",
    "destination_airport_id": 6,
    "destination_airport_code": "HYD",
    "price": 3466
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Jaipur",
    "destination_airport_id": 7,
    "destination_airport_code": "JAI",
    "price": 7233
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "lucknow",
    "destination_airport_id": 8,
    "destination_airport_code": "LKW",
    "price": 3275
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Kolkata",
    "destination_airport_id": 9,
    "destination_airport_code": "KOL",
    "price": 5245
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Chennai",
    "destination_airport_id": 10,
    "destination_airport_code": "CHE",
    "price": 3111
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Goa",
    "destination_airport_id": 11,
    "destination_airport_code": "GOA",
    "price": 9939
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Pune",
    "destination_airport_id": 1,
    "destination_airport_code": "PNQ",
    "price": 3085
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Mumbai",
    "destination_airport_id": 2,
    "destination_airport_code": "MUM",
    "price": 2367
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Ahmedabad",
    "destination_airport_id": 4,
    "destination_airport_code": "AHM",
    "price": 6187
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Banglore",
    "destination_airport_id": 5,
    "destination_airport_code": "BAN",
    "price": 5751
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Hyderabad",
    "destination_airport_id": 6,
    "destination_airport_code": "HYD",
    "price": 7190
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Jaipur",
    "destination_airport_id": 7,
    "destination_airport_code": "JAI",
    "price": 4507
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "lucknow",
    "destination_airport_id": 8,
    "destination_airport_code": "LKW",
    "price": 7666
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Kolkata",
    "destination_airport_id": 9,
    "destination_airport_code": "KOL",
    "price": 8708
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Chennai",
    "destination_airport_id": 10,
    "destination_airport_code": "CHE",
    "price": 3450
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Goa",
    "destination_airport_id": 11,
    "destination_airport_code": "GOA",
    "price": 4432
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Pune",
    "destination_airport_id": 1,
    "destination_airport_code": "PNQ",
    "price": 7136
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Mumbai",
    "destination_airport_id": 2,
    "destination_airport_code": "MUM",
    "price": 4157
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Ahmedabad",
    "destination_airport_id": 4,
    "destination_airport_code": "AHM",
    "price": 8659
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Banglore",
    "destination_airport_id": 5,
    "destination_airport_code": "BAN",
    "price": 6985
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Hyderabad",
    "destination_airport_id": 6,
    "destination_airport_code": "HYD",
    "price": 8221
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Jaipur",
    "destination_airport_id": 7,
    "destination_airport_code": "JAI",
    "price": 9936
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "lucknow",
    "destination_airport_id": 8,
    "destination_airport_code": "LKW",
    "price": 5171
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Kolkata",
    "destination_airport_id": 9,
    "destination_airport_code": "KOL",
    "price": 5224
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Chennai",
    "destination_airport_id": 10,
    "destination_airport_code": "CHE",
    "price": 2275
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Goa",
    "destination_airport_id": 11,
    "destination_airport_code": "GOA",
    "price": 2233
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Pune",
    "destination_airport_id": 1,
    "destination_airport_code": "PNQ",
    "price": 4289
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Mumbai",
    "destination_airport_id": 2,
    "destination_airport_code": "MUM",
    "price": 7557
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Ahmedabad",
    "destination_airport_id": 4,
    "destination_airport_code": "AHM",
    "price": 7603
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Banglore",
    "destination_airport_id": 5,
    "destination_airport_code": "BAN",
    "price": 2346
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Hyderabad",
    "destination_airport_id": 6,
    "destination_airport_code": "HYD",
    "price": 5084
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Jaipur",
    "destination_airport_id": 7,
    "destination_airport_code": "JAI",
    "price": 4211
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "lucknow",
    "destination_airport_id": 8,
    "destination_airport_code": "LKW",
    "price": 7901
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Kolkata",
    "destination_airport_id": 9,
    "destination_airport_code": "KOL",
    "price": 8067
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Chennai",
    "destination_airport_id": 10,
    "destination_airport_code": "CHE",
    "price": 5333
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Goa",
    "destination_airport_id": 11,
    "destination_airport_code": "GOA",
    "price": 7511
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Pune",
    "destination_airport_id": 1,
    "destination_airport_code": "PNQ",
    "price": 9405
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Mumbai",
    "destination_airport_id": 2,
    "destination_airport_code": "MUM",
    "price": 4287
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Ahmedabad",
    "destination_airport_id": 4,
    "destination_airport_code": "AHM",
    "price": 9566
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Banglore",
    "destination_airport_id": 5,
    "destination_airport_code": "BAN",
    "price": 5434
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Hyderabad",
    "destination_airport_id": 6,
    "destination_airport_code": "HYD",
    "price": 8959
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Jaipur",
    "destination_airport_id": 7,
    "destination_airport_code": "JAI",
    "price": 7911
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "lucknow",
    "destination_airport_id": 8,
    "destination_airport_code": "LKW",
    "price": 9039
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Kolkata",
    "destination_airport_id": 9,
    "destination_airport_code": "KOL",
    "price": 6179
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Chennai",
    "destination_airport_id": 10,
    "destination_airport_code": "CHE",
    "price": 2640
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Goa",
    "destination_airport_id": 11,
    "destination_airport_code": "GOA",
    "price": 6640
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Pune",
    "destination_airport_id": 1,
    "destination_airport_code": "PNQ",
    "price": 9530
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Mumbai",
    "destination_airport_id": 2,
    "destination_airport_code": "MUM",
    "price": 8008
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Ahmedabad",
    "destination_airport_id": 4,
    "destination_airport_code": "AHM",
    "price": 3828
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Banglore",
    "destination_airport_id": 5,
    "destination_airport_code": "BAN",
    "price": 8608
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Hyderabad",
    "destination_airport_id": 6,
    "destination_airport_code": "HYD",
    "price": 9072
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Jaipur",
    "destination_airport_id": 7,
    "destination_airport_code": "JAI",
    "price": 7795
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "lucknow",
    "destination_airport_id": 8,
    "destination_airport_code": "LKW",
    "price": 8070
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Kolkata",
    "destination_airport_id": 9,
    "destination_airport_code": "KOL",
    "price": 6799
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Chennai",
    "destination_airport_id": 10,
    "destination_airport_code": "CHE",
    "price": 3050
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Delhi",
    "source_airport_code": "DEL",
    "source_airport_id": 3,
    "destination_airport": "Goa",
    "destination_airport_id": 11,
    "destination_airport_code": "GOA",
    "price": 9412
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Pune",
    "destination_airport_id": 1,
    "destination_airport_code": "PNQ",
    "price": 3256
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Mumbai",
    "destination_airport_id": 2,
    "destination_airport_code": "MUM",
    "price": 7970
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Delhi",
    "destination_airport_id": 3,
    "destination_airport_code": "DEL",
    "price": 2815
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Banglore",
    "destination_airport_id": 5,
    "destination_airport_code": "BAN",
    "price": 3789
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Hyderabad",
    "destination_airport_id": 6,
    "destination_airport_code": "HYD",
    "price": 7185
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Jaipur",
    "destination_airport_id": 7,
    "destination_airport_code": "JAI",
    "price": 6241
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "lucknow",
    "destination_airport_id": 8,
    "destination_airport_code": "LKW",
    "price": 6266
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Kolkata",
    "destination_airport_id": 9,
    "destination_airport_code": "KOL",
    "price": 3199
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Chennai",
    "destination_airport_id": 10,
    "destination_airport_code": "CHE",
    "price": 6044
  },
  {
    "airline": "Jet Airways",
    "airline_id": 1,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Goa",
    "destination_airport_id": 11,
    "destination_airport_code": "GOA",
    "price": 2303
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Pune",
    "destination_airport_id": 1,
    "destination_airport_code": "PNQ",
    "price": 6675
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Mumbai",
    "destination_airport_id": 2,
    "destination_airport_code": "MUM",
    "price": 6328
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Delhi",
    "destination_airport_id": 3,
    "destination_airport_code": "DEL",
    "price": 4772
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Banglore",
    "destination_airport_id": 5,
    "destination_airport_code": "BAN",
    "price": 4677
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Hyderabad",
    "destination_airport_id": 6,
    "destination_airport_code": "HYD",
    "price": 5729
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Jaipur",
    "destination_airport_id": 7,
    "destination_airport_code": "JAI",
    "price": 4166
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "lucknow",
    "destination_airport_id": 8,
    "destination_airport_code": "LKW",
    "price": 4248
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Kolkata",
    "destination_airport_id": 9,
    "destination_airport_code": "KOL",
    "price": 6635
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Chennai",
    "destination_airport_id": 10,
    "destination_airport_code": "CHE",
    "price": 2349
  },
  {
    "airline": "Air India",
    "airline_id": 2,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Goa",
    "destination_airport_id": 11,
    "destination_airport_code": "GOA",
    "price": 9702
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Pune",
    "destination_airport_id": 1,
    "destination_airport_code": "PNQ",
    "price": 8214
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Mumbai",
    "destination_airport_id": 2,
    "destination_airport_code": "MUM",
    "price": 5948
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Delhi",
    "destination_airport_id": 3,
    "destination_airport_code": "DEL",
    "price": 6373
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Banglore",
    "destination_airport_id": 5,
    "destination_airport_code": "BAN",
    "price": 3682
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Hyderabad",
    "destination_airport_id": 6,
    "destination_airport_code": "HYD",
    "price": 5539
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Jaipur",
    "destination_airport_id": 7,
    "destination_airport_code": "JAI",
    "price": 6489
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "lucknow",
    "destination_airport_id": 8,
    "destination_airport_code": "LKW",
    "price": 7662
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Kolkata",
    "destination_airport_id": 9,
    "destination_airport_code": "KOL",
    "price": 6198
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Chennai",
    "destination_airport_id": 10,
    "destination_airport_code": "CHE",
    "price": 6354
  },
  {
    "airline": "Indigo",
    "airline_id": 3,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Goa",
    "destination_airport_id": 11,
    "destination_airport_code": "GOA",
    "price": 4230
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Pune",
    "destination_airport_id": 1,
    "destination_airport_code": "PNQ",
    "price": 3837
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Mumbai",
    "destination_airport_id": 2,
    "destination_airport_code": "MUM",
    "price": 6988
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Delhi",
    "destination_airport_id": 3,
    "destination_airport_code": "DEL",
    "price": 5295
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Banglore",
    "destination_airport_id": 5,
    "destination_airport_code": "BAN",
    "price": 6241
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Hyderabad",
    "destination_airport_id": 6,
    "destination_airport_code": "HYD",
    "price": 9807
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Jaipur",
    "destination_airport_id": 7,
    "destination_airport_code": "JAI",
    "price": 4173
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "lucknow",
    "destination_airport_id": 8,
    "destination_airport_code": "LKW",
    "price": 4115
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Kolkata",
    "destination_airport_id": 9,
    "destination_airport_code": "KOL",
    "price": 6158
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Chennai",
    "destination_airport_id": 10,
    "destination_airport_code": "CHE",
    "price": 5608
  },
  {
    "airline": "Spice",
    "airline_id": 4,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Goa",
    "destination_airport_id": 11,
    "destination_airport_code": "GOA",
    "price": 9877
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Pune",
    "destination_airport_id": 1,
    "destination_airport_code": "PNQ",
    "price": 3434
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Mumbai",
    "destination_airport_id": 2,
    "destination_airport_code": "MUM",
    "price": 3050
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Delhi",
    "destination_airport_id": 3,
    "destination_airport_code": "DEL",
    "price": 4773
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Banglore",
    "destination_airport_id": 5,
    "destination_airport_code": "BAN",
    "price": 5641
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Hyderabad",
    "destination_airport_id": 6,
    "destination_airport_code": "HYD",
    "price": 2916
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Jaipur",
    "destination_airport_id": 7,
    "destination_airport_code": "JAI",
    "price": 6599
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "lucknow",
    "destination_airport_id": 8,
    "destination_airport_code": "LKW",
    "price": 9524
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Kolkata",
    "destination_airport_id": 9,
    "destination_airport_code": "KOL",
    "price": 7380
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Chennai",
    "destination_airport_id": 10,
    "destination_airport_code": "CHE",
    "price": 7967
  },
  {
    "airline": "Go Air",
    "airline_id": 5,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Goa",
    "destination_airport_id": 11,
    "destination_airport_code": "GOA",
    "price": 9082
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Pune",
    "destination_airport_id": 1,
    "destination_airport_code": "PNQ",
    "price": 5617
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Mumbai",
    "destination_airport_id": 2,
    "destination_airport_code": "MUM",
    "price": 4698
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Delhi",
    "destination_airport_id": 3,
    "destination_airport_code": "DEL",
    "price": 7090
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Banglore",
    "destination_airport_id": 5,
    "destination_airport_code": "BAN",
    "price": 5423
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Hyderabad",
    "destination_airport_id": 6,
    "destination_airport_code": "HYD",
    "price": 9951
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Jaipur",
    "destination_airport_id": 7,
    "destination_airport_code": "JAI",
    "price": 2812
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "lucknow",
    "destination_airport_id": 8,
    "destination_airport_code": "LKW",
    "price": 8768
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Kolkata",
    "destination_airport_id": 9,
    "destination_airport_code": "KOL",
    "price": 2329
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Chennai",
    "destination_airport_id": 10,
    "destination_airport_code": "CHE",
    "price": 7533
  },
  {
    "airline": "Air Asia",
    "airline_id": 6,
    "source_airport": "Ahmedabad",
    "source_airport_code": "AHM",
    "source_airport_id": 4,
    "destination_airport": "Goa",
    "destination_airport_id": 11,
    "destination_airport_code": "GOA",
    "price": 7754
  }
];


export const airports =[
  {
    "airport": "Pune",
    "airport_id": 1,
    "airport_code": "PNQ"
  },
  {
    "airport": "Mumbai",
    "airport_id": 2,
    "airport_code": "MUM"
  },
  {
    "airport": "Delhi",
    "airport_id": 3,
    "airport_code": "DEL"
  },
  {
    "airport": "Ahmedabad",
    "airport_id": 4,
    "airport_code": "AHM"
  },
  {
    "airport": "Banglore",
    "airport_id": 5,
    "airport_code": "BAN"
  },
  {
    "airport": "Hyderabad",
    "airport_id": 6,
    "airport_code": "HYD"
  },
  {
    "airport": "Jaipur",
    "airport_id": 7,
    "airport_code": "JAI"
  },
  {
    "airport": "lucknow",
    "airport_id": 8,
    "airport_code": "LKW"
  },
  {
    "airport": "Kolkata",
    "airport_id": 9,
    "airport_code": "KOL"
  },
  {
    "airport": "Chennai",
    "airport_id": 10,
    "airport_code": "CHE"
  },
  {
    "airport": "Goa",
    "airport_id": 11,
    "airport_code": "GOA"
  }
];

var airlines=[
  {
    "airline": "Jet Airways",
    "airline_id": 1
  },
  {
    "airline": "Air India",
    "airline_id": 2
  },
  {
    "airline": "Indigo",
    "airline_id": 3
  },
  {
    "airline": "Spice",
    "airline_id": 4
  },
  {
    "airline": "Go Air",
    "airline_id": 5
  },
  {
    "airline": "Air Asia",
    "airline_id": 6
  }
];